# Generated by Django 4.2.5 on 2023-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='self_invite',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='инвайт код'),
        ),
    ]
