# Generated by Django 4.2.5 on 2023-09-14 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_self_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='received_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='полученный инвайт код'),
        ),
    ]
